version: "3.9"
services:
  dev:
    build:
      context: .
      target: dev
    container_name: static-app-dev
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

  server:
    build:
      context: .
      target: build
    container_name: app-server
    environment:
      - BUILD_STAGE=build
    ports:
      - "8081:3000"
    restart: always

  # uncomment the following lines to serve static assets separately
  # static:
  #   build:
  #     context: .
  #     target: serve
  #   container_name: app-static
  #   environment:
  #     - BUILD_STAGE=static
  #   depends_on:
  #     - server
  #   ports:
  #     - "8080:8080"
  #   restart: always
